--BEGIN NC辅料档案对照表
CREATE TABLE "NBADV"."TRA_AUXI_MATERIAL_TEMP"
 ("NAME"     VARCHAR(100),
  "PK_CORP"  VARCHAR(20),
  "ID"       INTEGER
 )
  DATA CAPTURE NONE
 IN "USERSPACE3"
  CCSID UNICODE@

ALTER TABLE "NBADV"."TRA_AUXI_MATERIAL_TEMP"
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE
  LOG INDEX BUILD NULL@

COMMENT ON "NBADV"."TRA_AUXI_MATERIAL_TEMP"
 ("NAME" IS '名称',
  "PK_CORP" IS '主键',
  "ID" IS 'id'
 )@
--END NC辅料档案对照表

--BEGIN NC辅料采购单主表
CREATE TABLE "NBADV"."TRA_FL_ORDER_MAIN_TEMP"
 ("PK_CORP"        VARCHAR(20)     NOT NULL,
  "BILLCODE"       VARCHAR(50),
  "BILLDATE"       DATE,
  "SUPPLIER"       VARCHAR(20),
  "SENDCOMPANY"    VARCHAR(20),
  "OPERATOR"       VARCHAR(20),
  "MAKEDATE"       DATE,
  "COUNTERMAN"     VARCHAR(20),
  "DEPT"           VARCHAR(20),
  "MEMO"           VARCHAR(1000),
  "ISCLOSED"       VARCHAR(10),
  "SENDCOMPANYID"  INTEGER,
  "OPERATORID"     INTEGER,
  "COUNTERMANID"   INTEGER,
  "DEPARTID"       INTEGER,
  "SUPPLIERID"     INTEGER,
  "ISPROCESSED"    VARCHAR(1)      NOT NULL  DEFAULT 'N'
 )
  DATA CAPTURE NONE
 IN "USERSPACE3"
  CCSID UNICODE@

ALTER TABLE "NBADV"."TRA_FL_ORDER_MAIN_TEMP"
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE
  LOG INDEX BUILD NULL@

COMMENT ON "NBADV"."TRA_FL_ORDER_MAIN_TEMP"
 ("PK_CORP" IS 'NC主键',
  "BILLCODE" IS '单据编号',
  "BILLDATE" IS '单据日期',
  "SUPPLIER" IS '供应商id from NC',
  "SENDCOMPANY" IS '发货公司id from NC',
  "OPERATOR" IS '制单人id from NC',
  "MAKEDATE" IS '制单日期',
  "COUNTERMAN" IS '业务员id from NC',
  "DEPT" IS '部门id from NC',
  "MEMO" IS '备注',
  "ISCLOSED" IS '是否关闭',
  "SENDCOMPANYID" IS '发货公司id from base platform',
  "OPERATORID" IS '制单人id from base platform',
  "COUNTERMANID" IS '业务员id from base platform',
  "DEPARTID" IS '部门id from base platform',
  "SUPPLIERID" IS '供应商id from base platform',
  "ISPROCESSED" IS '是否已经做过ID转换加工(Y是,N否)'
 )@
--END NC辅料采购单主表

--BEGIN NC辅料采购单细表CREATE TABLE "NBADV"."TRA_FL_ORDER_DETAIL_TEMP"
 ("PK_CORP"           VARCHAR(20)     NOT NULL,
  "PK_CORP_D"         VARCHAR(20)     NOT NULL,
  "MATERIAL"          VARCHAR(20),
  "STANDARD"          VARCHAR(100),
  "MAINMEASUNIT"      VARCHAR(20),
  "WEIGHT"            DECIMAL(19, 6),
  "MEASCONVRATE"      DECIMAL(19, 6),
  "AUXIMEASUNIT"      VARCHAR(20),
  "QTY"               DECIMAL(19, 6),
  "CROWNO"            INTEGER,
  "MEMO"              VARCHAR(1000),
  "ISCLOSED"          VARCHAR(1),
  "RECEIVECOMPANY"    VARCHAR(20),
  "MANUFACTURER"      VARCHAR(20),
  "MATERIALID"        INTEGER,
  "MAINUNIT"          INTEGER,
  "AUXIUNIT"          INTEGER,
  "RECEIVECOMPANYID"  INTEGER,
  "MANUFACTURERID"    INTEGER,
  "ISPROCESSED"       VARCHAR(1)                DEFAULT 'N',
  "ISSYNC"            VARCHAR(1)                DEFAULT 'N'
 )
  DATA CAPTURE NONE
 IN "USERSPACE3"
  CCSID UNICODE@

ALTER TABLE "NBADV"."TRA_FL_ORDER_DETAIL_TEMP"
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE
  LOG INDEX BUILD NULL@

COMMENT ON "NBADV"."TRA_FL_ORDER_DETAIL_TEMP"
 ("PK_CORP" IS '主表id from NC',
  "PK_CORP_D" IS '细表id from NC',
  "MATERIAL" IS '物料id from NC',
  "STANDARD" IS '包装规格',
  "MAINMEASUNIT" IS '主计量单位id from NC',
  "WEIGHT" IS '主数量',
  "MEASCONVRATE" IS '主辅换算率',
  "AUXIMEASUNIT" IS '辅计量单位id from NC',
  "QTY" IS '辅数量',
  "CROWNO" IS '行号',
  "MEMO" IS '备注',
  "ISCLOSED" IS '是否关闭(Y是,N否)',
  "RECEIVECOMPANY" IS '收货公司id from NC',
  "MANUFACTURER" IS '加工商id from NC',
  "MATERIALID" IS '物料ID',
  "MAINUNIT" IS '主计量单位',
  "AUXIUNIT" IS '辅计量单位',
  "RECEIVECOMPANYID" IS '收货公司',
  "MANUFACTURERID" IS '加工商',
  "ISPROCESSED" IS '是否已经做过ID转换加工(Y是,N否)',
  "ISSYNC" IS '是否同步进对应的业务数据表(Y是,N否)'
 )@
--END NC辅料采购单细表